import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_ORIGIN||'http://127.0.0.1:3077';
await page.goto(base);await page.getByRole('heading',{name:'Training topics'}).waitFor();
await page.getByRole('button',{name:/Password Reset/}).waitFor();
await page.screenshot({path:'/tmp/sidekick-home-updated.png',fullPage:true});
await page.getByRole('button',{name:'Close navigation'}).click();
await page.reload();await page.getByRole('button',{name:'Open navigation'}).waitFor();
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByLabel('Search training topics and notes').fill('MFA');assert.equal(await page.locator('.topic').count(),1);
await page.getByRole('button',{name:'Clear topic search'}).click();
await page.getByRole('button',{name:/Password Reset/}).click();
assert.match(page.url(),/topics\/password/);await page.getByRole('heading',{name:'Juniper network password reset'}).waitFor();
await page.getByLabel('Ask about Password Reset').fill('Password reset');await page.getByRole('button',{name:'Search this topic'}).click();
await page.getByRole('button',{name:'Network password',exact:true}).click();await page.locator('.topic-result').getByRole('heading',{name:'Juniper network password reset'}).waitFor();
await page.getByLabel('Ask about Password Reset').fill('How do I reset MFA?');await page.getByRole('button',{name:'Search this topic'}).click();await page.getByRole('heading',{name:'Not covered in this topic’s training.'}).waitFor();
await page.screenshot({path:'/tmp/sidekick-topic-updated.png',fullPage:true});
await page.getByRole('link',{name:'AI Assistant',exact:true}).click();
await page.getByLabel('Ask the training assistant').fill('User cannot access the system');await page.getByRole('button',{name:'Send question'}).click();await page.getByRole('button',{name:'VPN',exact:true}).click();await page.getByRole('heading',{name:'Contractor VPN access'}).waitFor();
await page.screenshot({path:'/tmp/sidekick-assistant-updated.png',fullPage:true});
await page.getByRole('button',{name:'Clear conversation'}).click();await page.getByRole('heading',{name:'How can I help?'}).waitFor();
await page.getByRole('link',{name:'Quick Links',exact:true}).click();await page.getByRole('heading',{name:'Quick Links'}).waitFor();await page.getByLabel('Search tools and websites').fill('meeting');assert.equal(await page.locator('.link-card').count(),1);
await page.setViewportSize({width:390,height:844});await page.goto(base);await page.getByRole('button',{name:'Close navigation'}).click();await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('link',{name:'AI Assistant',exact:true}).click();await page.getByRole('button',{name:'Open navigation'}).waitFor();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.screenshot({path:'/tmp/sidekick-mobile-updated.png',fullPage:true});assert.deepEqual(errors,[]);
await browser.close();console.log('Desktop and mobile acceptance passed');
