import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
await page.context().grantPermissions(['clipboard-read','clipboard-write']);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_ORIGIN||'http://127.0.0.1:3077';
await page.goto(base);await page.getByRole('heading',{name:'Training topics'}).waitFor();
await page.getByRole('button',{name:/AD Password Reset/}).waitFor();
await page.screenshot({path:'/tmp/sidekick-home-updated.png',fullPage:true});
await page.getByRole('button',{name:'Close navigation'}).click();
await page.reload();await page.getByRole('button',{name:'Open navigation'}).waitFor();
await page.getByRole('button',{name:'Open navigation'}).click();
await page.getByLabel('Search training topics and notes').fill('P3 incident');assert.equal(await page.locator('.topic').count(),1);
await page.getByRole('button',{name:'Clear topic search'}).click();
const topicCalls=[];page.on('request',request=>{if(request.method()==='POST')topicCalls.push(new URL(request.url()).pathname)});
await page.getByRole('button',{name:/Concur Support/}).click();
await page.getByRole('heading',{name:'Concur application support routing'}).waitFor();
await page.getByLabel('Ask about Concur Support').fill('Where should I route a Concur sign-in issue?');
await page.getByRole('button',{name:'Search this topic'}).click();
await page.locator('.topic-result').getByRole('heading',{name:'Concur application support routing'}).waitFor();
assert.match(page.url(),/topics\/concur/);
assert.ok(topicCalls.includes('/api/topics/concur/ask'));
assert.ok(!topicCalls.includes('/api/assistant'));
await page.getByLabel('Ask about Concur Support').fill('How do I reset BitLocker?');
await page.getByRole('button',{name:'Search this topic'}).click();
await page.getByRole('heading',{name:'Not covered in this topic’s training.'}).waitFor();
assert.match(page.url(),/topics\/concur/);
await page.getByRole('link',{name:/All topics/}).click();
await page.getByRole('button',{name:/Software Center/}).click();
await page.getByRole('heading',{name:'Software Center: session introduction'}).waitFor();
await page.getByLabel('Ask about Software Center').fill('What are the Software Center installation steps?');
await page.getByRole('button',{name:'Search this topic'}).click();
await page.locator('.topic-result').getByRole('heading',{name:'Software Center: session introduction'}).waitFor();
assert.match(page.url(),/topics\/software-center/);
await page.getByRole('link',{name:/All topics/}).click();
await page.getByRole('button',{name:/AD Password Reset/}).click();
assert.match(page.url(),/topics\/password/);await page.getByRole('heading',{name:'Juniper network password reset'}).waitFor();
await page.getByLabel('Ask about AD Password Reset').fill('Password reset');await page.getByRole('button',{name:'Search this topic'}).click();
await page.getByRole('button',{name:'Network password',exact:true}).click();await page.locator('.topic-result').getByRole('heading',{name:'Juniper network password reset'}).waitFor();
await page.getByLabel('Ask about AD Password Reset').fill('How do I reset MFA?');await page.getByRole('button',{name:'Search this topic'}).click();await page.getByRole('heading',{name:'Not covered in this topic’s training.'}).waitFor();
await page.screenshot({path:'/tmp/sidekick-topic-updated.png',fullPage:true});
await page.getByRole('button',{name:'Copy notes'}).first().click();await page.getByRole('button',{name:'Copied',exact:true}).waitFor();
await page.getByRole('link',{name:'AI Assistant',exact:true}).click();
await page.getByLabel('Ask the training assistant').fill('User cannot access the system');await page.getByRole('button',{name:'Send question'}).click();await page.getByRole('button',{name:'VPN',exact:true}).click();await page.getByRole('heading',{name:'Contractor VPN access'}).waitFor();
await page.screenshot({path:'/tmp/sidekick-assistant-updated.png',fullPage:true});
await page.getByRole('button',{name:'Clear conversation'}).click();await page.getByRole('heading',{name:'How can I help?'}).waitFor();
await page.getByRole('link',{name:'Quick Links',exact:true}).click();await page.getByRole('heading',{name:'Quick Links'}).waitFor();await page.getByLabel('Search tools and websites').fill('Teams');assert.equal(await page.locator('.link-card').count(),1);
await page.getByLabel('Search tools and websites').fill('My Groups');await page.getByRole('link',{name:'Open training notes'}).click();await page.getByRole('heading',{name:'My Groups & VPN Roles',exact:true}).waitFor();
await page.setViewportSize({width:390,height:844});await page.goto(base);await page.getByRole('button',{name:'Close navigation'}).click();await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('link',{name:'AI Assistant',exact:true}).click();await page.getByRole('button',{name:'Open navigation'}).waitFor();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.locator('.sidebar').evaluate(async el=>{await Promise.all(el.getAnimations().map(a=>a.finished))});
assert.equal(await page.locator('.sidebar-toggle svg').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=52}),true);
await page.screenshot({path:'/tmp/sidekick-mobile-updated.png',fullPage:true});assert.deepEqual(errors,[]);
await browser.close();console.log('Desktop and mobile acceptance passed');
